Add more icons on the table columns name
RalitsaTerzieva/calcalc pull request #4
Opened 2021-08-27 14:47 UTC by RalitsaTerzieva

Add 3 new icons to the table because it is more fancy this way. I use for this react-icons. @strongholder

2021-08-29 17:24 UTC, strongholder requested changes
Good job! It will work as expected after you fix the `io5` import. As a future improvement I suggest that we add some padding around the text in the column headers and maybe improve the color palette by picking the colors from some generator such as: https://coolors.co/palettes/trending

2021-08-29 17:24 UTC, strongholder commented on src/Calculator.jsx
> +import { IoFastFood } from "react-icons/Io";
You need to fix the name of the module because the `IoFastFood` icon is located in the `react-icons/io5` module which is described here: https://react-icons.github.io/react-icons/icons?name=io5
```suggestion
import { IoFastFood } from "react-icons/io5";
```

2021-08-29 17:24 UTC, strongholder commented on src/Calculator.jsx
> +import { FaWeightHanging, FaWeight } from "react-icons/fa";
```suggestion
import { FaWeightHanging, FaWeight, FaCalculator } from "react-icons/fa";
```

2021-08-29 17:24 UTC, strongholder commented on src/Calculator.jsx
>                      <th>Total</th>
I think that it would be more consistent if we add an icon to the total column as well. Feel free to choose another column that you like more.
```suggestion
                   <th><FaCalculator /> Total</th>
```

2021-09-11 15:26 UTC, RalitsaTerzieva commented on src/Calculator.jsx
>                      <th>Total</th>
Amazing idea! I will add it to the code. :)

2021-09-11 16:41 UTC, merged